feat(lib): upgrade to angular 10
d3lm/ngx-drag-to-select pull request #110
Opened 2020-10-23 19:53 UTC by cyclist82

2020-10-26 10:02 UTC, d3lm commented
This looks pretty good. Thanks for the PR! I thought about removing RxJS as a peer-dependency but I think we should keep it in there. Modern package managers install the peer dependencies anyways, and it's no longer a user concern, at least npm 7 does that now and from what I read, it was a big mistake not to install them in the first place. Keeping RxJS as a peer-dep makes it more complete IMO. Curious to hear your thoughts.

If you agree, can you add it back in and just update the version? Then this PR is good to go and I ll go ahead and merge it.

2020-10-26 15:42 UTC, cyclist82 commented
Thanks a lot for your remarks @d3lm. I'm absolutely fine with adding RxJS as a peer-dependency. I'll add a commit soon.

When you'll do the next release with these changes are you going to mention the lost support for angular 6 and 7 in the release notes?

2020-10-27 08:12 UTC, d3lm requested changes
Thanks! One last thing, which is we need to update the readme as well. Maybe we can add a section to the bottom about the support for Angular 6 and 7, and that this upgrade, as you mentioned, no longer supports Angular < 8. And we won't backport new features, only severe issues. So if people want the latest and greatest, they have to update to at least Angular 8.x.

There is already a section for "support for Angular 5.x", maybe we can add another one for "Angular 6 and 7". 

To also mention this in the changelog, can you please update your commit message to contain the breaking change as well? As in:

```
feat(lib): upgrade to angular 10

BREAKING CHANGE: dropping support for Angular < 8.x
```

Many thanks!

2020-10-27 15:56 UTC, cyclist82 commented
Thanks for the tips. 

I added the requested changes to the commit message and updated the README. Please have a look if you like the changes @d3lm.

2020-10-27 17:36 UTC, d3lm requested changes
We are getting there! Sorry for all the remarks. You're doing an amazing work here. Thanks so much for hanging in there and implementing all my feedback.

2020-10-27 17:36 UTC, d3lm commented on README.md
> +### Does this library work with Angular Versions < 8.0.0?
Maybe we go with a more general title, something along the lines of `Can I use this library with an older version of Angular?`

2020-10-27 17:36 UTC, d3lm commented on README.md
> +Please have a look here to see which version supports your angular application.
I'd re-write this to something like (given we use the title I suggested):

```
Yep you totally can! But this also means you won't be able to use the latest and greatest and all of the newer features. The reason for this is that we are not back porting new features to older versions of this library, due to maintenance overhead. Severe bugs and security issues, however, are back ported.

What does that mean for you now? We recommend to stay up to date with new Angular versions. If for some reasons you can't then here's an overview versions you could use with older versions of Angular:

<TABLE>

To install a specific version run for example `npm install ngx-drag-to-select@x.x.x`.
```

And then we can also get rid of the sentence below the table.

2020-10-27 17:36 UTC, d3lm commented on README.md
> +| Angular Version      | ngx-drag-to-select Version |
Great idea! Thanks for this addition.

2020-10-27 17:36 UTC, d3lm commented on README.md
> +| 5.x.x                |                      1.1.1 |
I would use version ranges, e.g. `<= 1.1.1`.

2020-10-27 17:36 UTC, d3lm commented on README.md
> +| 6.x.x - 7.x.x        |                      3.1.1 |
Same here => `> 1.1.1 <= 3.1.1`

2020-10-27 17:36 UTC, d3lm commented on README.md
> +| 6.x.x - 7.x.x        |                      3.1.1 |
And also add a new row with

```
>= 8.x.x              >= 4.0.0
```

2020-10-27 18:09 UTC, cyclist82 commented
Thanks again for the nice feedback and your help to properly document the change in the docs. 

I added the proposed changes to the `README`. Please have another look @d3lm.

2020-10-27 19:00 UTC, d3lm requested changes
Last remarks, promised 😂 👍

2020-10-27 19:00 UTC, d3lm commented on README.md
> +| Angular Version      | ngx-drag-to-select Version |
Let's change the headers to only `Angular` and `ngx-drag-to-select`. The "version" can be inferred by the user very quickly by looking at the rows.

2020-10-28 07:48 UTC, d3lm approved these changes
This looks good to me! Well done and thanks for your work 🙏

2020-10-28 07:51 UTC, merged