feat(lib): add input to control select on click
d3lm/ngx-drag-to-select pull request #129
Opened 2021-06-23 09:47 UTC by sam-eah

This small PR gives the ability to chose wether an item should be selected by clicking on it. This is done using a new input,  `selectOnClick` in `dts-select-container`.  
I'm using this library with some custom drag & drop for a file explorer project. I need to be able to drag & drop all selected items together, however at the current state it is not possible, since starting to drag will unselect all other items. This fixes this issue.  

Thanks again for the awesome work :)

2021-06-24 07:00 UTC, d3lm commented
Hey! Thanks for the PR. I am not sure I understand cause you can use the `selectMode`, see https://github.com/d3lm/ngx-drag-to-select#dts-select-container. Have you tried to enable that?

2021-06-24 07:06 UTC, d3lm commented
Strange. I just looked at the linting error and it's a little weird.

2021-06-28 08:09 UTC, sam-eah commented
> Do you simply want to disable selection on click but still be able to drag to select items?  

Yes, exactly !

2021-06-28 12:21 UTC, d3lm commented
Makes sense. I am down to continue with this PR if you add tests and fix CI.

2021-07-01 12:53 UTC, sam-eah commented
It's a bit strange, I juste tried the cypress tests on my local server and they all passed 
![e2e](https://user-images.githubusercontent.com/15243807/124127264-ccfe9100-da7b-11eb-81b7-78afedaa02f8.PNG)
And I got no errors from linting or styling with the commands `style` and `lint:check` either  
Do you have any idea ?

2021-07-01 20:56 UTC, d3lm commented
Hm that's indeed very strange. I can look into this on the weekend if I find the time and give it a try on my machine.

2021-07-01 20:56 UTC, d3lm commented
I have also restarted all jobs. Maybe that helps 🤷‍♂️

2021-07-02 07:39 UTC, sam-eah commented
> I have also restarted all jobs. Maybe that helps 🤷‍♂️

Okay now all Cypress tests pass!  
But the lint task still fails: `npm ERR! code ELIFECYCLE`
I would typically try these commands for this error, but I'm not sure how github CI pipelines handle node modules 😓 
- `npm cache clean --force`
- `rm -rf node_modules package-lock.json`
- `npm install`

2021-08-16 14:25 UTC, sam-eah commented
Hello, any updates ?

2021-08-17 08:09 UTC, d3lm commented
Sorry for my late response. Been super busy lately. I try to have a look this week to see if I can find out why the Lint stage fails and how I can fix it. It also fails in another PR 🤔

2021-08-17 09:36 UTC, sam-eah commented
No worries, thanks for your time!

2021-08-28 07:46 UTC, d3lm requested changes
I reviewed your PR and have a small nitpick. Also, please add e2e tests for this feature.

2021-08-28 07:46 UTC, d3lm commented on README.md
> +| selectOnClick         | Boolean    | `true`  | Whether items should be selected when clicking them                                                           |
```suggestion
| selectOnClick         | Boolean    | `true`  | Whether items should be selected when clicked                                                           |
```

2021-09-01 09:55 UTC, d3lm commented
I just merged another PR. Please rebase this PR again on latest master. Thanks!

2021-09-11 14:16 UTC, d3lm requested changes
Ok this looks good, but can you please add some e2e tests for this?

2021-09-17 08:04 UTC, sam-eah commented
Hello, I've added some e2e tests, please tell me if this suits you

2021-09-17 09:23 UTC, d3lm requested changes
Yep this looks good. Thanks for adding a test. Left one minor comment.

2021-09-17 09:23 UTC, d3lm commented on cypress/integration/clicking.spec.ts
> +      disableSelectOnClick();
Can you add a newline after this?

2021-09-17 12:14 UTC, sam-eah commented on cypress/integration/clicking.spec.ts
> +      disableSelectOnClick();
```suggestion
      disableSelectOnClick();
      
```
Like this?

2021-09-17 20:04 UTC, d3lm commented on cypress/integration/clicking.spec.ts
> +      disableSelectOnClick();
Yup 👍

2021-09-19 07:04 UTC, d3lm approved these changes

2021-09-19 07:18 UTC, merged

2021-09-20 05:06 UTC, sam-eah commented
Awesome! Do you know when a new npm version can be released?

2021-09-20 07:24 UTC, d3lm commented
It's now published. You can grab 4.2.0.

2021-09-20 20:20 UTC, sam-eah commented
Amazing, thanks!