feat(lib): add disabled state for select item
d3lm/ngx-drag-to-select pull request #130
Opened 2021-08-10 07:24 UTC by ennjin

Closes #71

2021-08-11 09:11 UTC, ennjin commented
@d3lm Hey. Can you take a look at this, please?

2021-08-17 08:08 UTC, d3lm requested changes
Thanks for the PR! Very much appreciated. Left a few small comments. Otherwise it looks good 👍

2021-08-17 08:08 UTC, d3lm commented on README.md
> +| dtsDisabled   | boolean  | false              | Disable selection for item                   |
I'd like to change the description to something like `Whether the item is selectable or not`.

2021-08-17 08:08 UTC, d3lm commented on projects/ngx-drag-to-select/src/lib/select-container.spec.ts
> +      selectContainerInstance.selectAll();
Please add a newline before.

2021-08-17 08:08 UTC, d3lm commented on src/app/app.component.html
> +    <mat-checkbox data-cy="useDisableCondition" [(ngModel)]="useDisableCondition">Disable condition (even)</mat-checkbox>
For the text of the checkbox let's just say `Disable even items`.

2021-08-17 08:08 UTC, d3lm commented on src/app/app.component.html
> +    <mat-checkbox data-cy="useDisableCondition" [(ngModel)]="useDisableCondition">Disable condition (even)</mat-checkbox>
Also could you change `useDisableCondition` to `disableEvenItems`

2021-08-17 08:46 UTC, ennjin commented
Hi. I've updated the notes above :)

2021-08-30 07:13 UTC, ennjin commented
There're latest changes from master branch.

2021-08-30 12:58 UTC, d3lm requested changes
This looks good. One last thing, could you also add an e2e test for this? 🙏

2021-08-30 12:58 UTC, d3lm commented on projects/ngx-drag-to-select/src/lib/select-item.directive.ts
> +  @Input()
It's a nitpick but can you please change the order here
```suggestion
  @Input()
  @HostBinding('class.dts-disabled')
```

2021-08-30 13:59 UTC, ennjin commented
Updated!

2021-08-31 18:48 UTC, d3lm requested changes
Awesome work! One last small thing.

2021-08-31 18:48 UTC, d3lm commented on cypress/integration/styling-and-classes.spec.ts
> +  it.only('should add `.dts-disabled` class to disabled items', () => {
Nitpick: I have used single quotes in the description of other tests so I'd like to streamline this:
```suggestion
  it.only(`should add 'dts-disabled' to disabled items`, () => {
```

2021-09-01 08:11 UTC, d3lm requested changes

2021-09-01 08:11 UTC, d3lm commented on cypress/integration/styling-and-classes.spec.ts
> +  it(`should add '.dts-disabled' class to disabled items`, () => {
Just say `'dts-disabled'`, that's what I did for all the other tests as well.
```suggestion
  it(`should add 'dts-disabled' class to disabled items`, () => {
```

2021-09-01 09:54 UTC, d3lm approved these changes

2021-09-01 09:54 UTC, merged

2021-09-01 09:55 UTC, d3lm commented
Merged! Thanks a lot for this PR 🙏

2021-09-01 10:42 UTC, ennjin commented
@d3lm Thanks! I'm wondering if could you bump the new changes to the NPM?

2021-09-01 11:01 UTC, d3lm commented
Definitely. I am trying to push on the other PR too so I can cut a single release that includes both new features.

2021-09-01 11:01 UTC, d3lm commented
It's this one #129.

2021-09-03 15:15 UTC, d3lm commented
I am not hearing anything, so maybe we can cut a release already. Alternatively you could pick up the PR and we can get it over the finish line.

2021-09-06 07:10 UTC, ennjin commented
> I am not hearing anything, so maybe we can cut a release already

Yep, it would be nice if we released it

2021-09-08 08:38 UTC, ennjin commented
So, will you bump the new version?

2021-09-20 07:24 UTC, d3lm commented
It's now published. You can grab 4.2.0.