fix(lib): keep selection when selectableItems change (#139)
d3lm/ngx-drag-to-select pull request #142
Opened 2021-09-22 12:55 UTC by lemmywrap

Pull request which fixes #139

2021-09-22 19:48 UTC, d3lm commented on projects/ngx-drag-to-select/src/lib/select-container.component.ts
> +      this.itemDeselected.emit(value);
Good catch!

2021-09-22 19:54 UTC, d3lm commented
Nice! Thanks for this PR 🙏 Really appreciate it 💯

2021-09-22 19:55 UTC, d3lm requested changes
Looks good! Only some minor style requests.

2021-09-22 19:55 UTC, d3lm commented on projects/ngx-drag-to-select/src/lib/select-container.spec.ts
> +    selectContainerInstance.itemDeselected.subscribe((item: SelectItemValue) => {
Newline before.

2021-09-22 19:55 UTC, d3lm commented on projects/ngx-drag-to-select/src/lib/select-container.spec.ts
> +    fixture.detectChanges();
Add some newlines here
```suggestion
    const previousData = testComponent.data$.value;
    
    testComponent.data$.next([previousData[1], previousData[2], { id: 4 }]);
    
    fixture.detectChanges();
```

2021-09-23 12:22 UTC, lemmywrap commented
Happy to contribute :)
I've added the newlines.

2021-11-01 09:45 UTC, lemmywrap commented
Two weekends later... ;)
I'll just keep reminding you, @d3lm !

2021-12-02 02:01 UTC, gavinharriss commented
Looks like a fix I could use as well. can't work out why the pull request isn't merged though?

2021-12-02 10:13 UTC, TheGlockZentix commented
Would be awesome if we could get this merged @d3lm! ⭐

2021-12-05 14:58 UTC, merged

2021-12-05 15:00 UTC, d3lm commented
Ok, I have done some general maintenance over the weekend and finally merged this PR. Thanks for collaborating!

2021-12-05 17:19 UTC, d3lm commented
For your information, this is available in `v4.2.1` and it's published to npm.